language: php

php:
  - 5.5

install:
  - composer install --optimize-autoloader --quiet

script: 
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-text

after_success:
  - bash <(curl -s https://codecov.io/bash)